[profile.default]
solc = "0.8.22"
src = "src"
out = "out"
libs = ["lib"]

evm_version = "paris"

[rpc_endpoints]
polygon = "https://polygon-mumbai.g.alchemy.com/v2/${API_KEY_RPC_POLYGON}"
mumbai = "https://polygon-mumbai.g.alchemy.com/v2/${API_KEY_RPC_MUMBAI}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${API_KEY_RPC_SEPOLIA}"
